version: '3.9'

services:
  db:
    image: postgres:16
    container_name: permisos_db
    restart: always
    environment:
      POSTGRES_DB: permisos
      POSTGRES_USER: permisos_user
      POSTGRES_PASSWORD: permisos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
